Repository teamwarren/blacktechdaily, pull requests merged in 2020-10, with the labels that each got.

#1 feat: call newsApi
  package.json
  src/App.css
  src/App.js
  src/components/articles-feed/articles-feed.jsx
  src/logo.svg
  yarn.lock
Labels: enhancement

#7 feat: add dark mode button with state and footer component
  .gitignore
  src/App.css
  src/App.js
  src/components/articles-feed/articles-feed.jsx
  src/components/footer/footer.css
  src/components/footer/footer.jsx
Labels: hacktoberfest-accepted

#8 Dark mode styles
  src/App.css
  src/App.js
  src/components/articles-feed/articles-feed.css
  src/components/articles-feed/articles-feed.jsx
Labels: enhancement, hacktoberfest-accepted

#9 Feature: Add Footer Component
  src/App.js
  src/components/footer/footer.css
  src/components/footer/footer.jsx
Labels: enhancement, hacktoberfest-accepted

#10 fix: add titles and sort by date
  package.json
  src/components/articles-feed/articles-feed.css
  src/components/articles-feed/articles-feed.jsx
  src/components/articles-feed/articles.config.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#13 fix: remove duplicate articles
  github/pull_request_template.md
  src/App.css
  src/components/articles-feed/articles-feed.css
  src/components/articles-feed/articles-feed.jsx
  src/components/footer/footer.css
  src/components/footer/footer.jsx
Labels: enhancement, hacktoberfest-accepted

#14 styles: add styled button component
  src/App.css
  src/App.js
  src/components/button/button.css
  src/components/button/button.jsx
Labels: enhancement, hacktoberfest-accepted

#15 version 0.2.0 release
  .gitignore
  README.md
  github/pull_request_template.md
  package.json
  src/App.css
  src/App.js
  src/components/articles-feed/articles-feed.css
  src/components/articles-feed/articles-feed.jsx
  src/components/articles-feed/articles.config.js
  src/components/button/button.css
  src/components/button/button.jsx
  src/components/footer/footer.css
  src/components/footer/footer.jsx
  yarn.lock
Labels: enhancement, hacktoberfest-accepted
